language: python
python: 3.5

env:
    - TOXENV=flake8
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35

matrix:
    fast_finish: true

    include:
        - python: 3.6-dev
          env: TOXENV=py36
        - python: 3.7-dev
          env: TOXENV=py37
        - python: pypy-5.4
          env: TOXENV=pypy_54
        - python: pypy3.3-5.2-alpha1
          env: TOXENV=pypy33

    allow_failures:
        - env: TOXENV=py26
        - env: TOXENV=py37
        - env: TOXENV=pypy_54
        - env: TOXENV=pypy33

install:
    - pip install tox codecov

script:
    - tox

after_success:
    - codecov

notifications:
    email: false
